### PR TITLE
Adding export visitPreprocessedAst & Fixing preprocess defined without paren bug

### PR DESCRIPTION
**Pull request by 06wj**

### CODE REVIEW

**Comment by AndrewRayCode** [comment]
Thanks for this! I'm surprised missing the `defined MACRO` condition without parens went unnoticed for so long. 

I'm going to refactor this slightly, the GLSL grammar has a `terminal` production used for this very case of ensuring a word boundary between a token and the next text.

**Comment by AndrewRayCode** [comment]
Published in `3.2.0`

**Comment by 06wj** [comment]
I used it for preprocess my shader code.
My shader controls the shader logic on different platforms through defines. 
```
#ifdef IN_WEB
web logic...
#else
native logic...
#endif
```
I want preprocess it so that it contain only the logic for a specific platform.

https://github.com/06wj/glsl-parser/blob/81524e31859bdc19e434c97c9109451db0e3ab70/src/preprocessor/preprocessor.test.ts#L517

**Comment by 06wj** [comment]
https://github.com/BabylonJS/Spector.js/pull/295
I added preprocessing functionality to SpectorJS using this library."

**Pull request merged**
