### PR TITLE
Implement location data for scopes

### PR DESCRIPTION
**Pull request by Lutymane**
In continuation to implementing locations for nodes, I added locations for scopes as well

### CODE REVIEW

**Comment by AndrewRayCode** [comment]
Awesome, thank you!

**Comment by AndrewRayCode** [comment]
I also refactored the includeLocation checks into `makeScope` and `setScopeEnd` https://github.com/ShaderFrog/glsl-parser/pull/10/files and added some tests

**Comment by AndrewRayCode** [comment]
Published in `@shaderfrog/glsl-parser@1.4.0`

**Comment by Lutymane** [comment]
> Awesome, thank you! What are you using the parser for, if you don't mind me asking?

@AndrewRayCode I'm building a nice IntelliSense for GLSL 😄 I made more tweaks to the code locally, like building native ES modules instead of CommonJS and using Maps in scopes instead of objects. Let me know if you'd consider adding these changes too

**Comment by AndrewRayCode** [comment]
> like building native ES modules instead of CommonJS 

What's your motivation here, and how do you handle the change? I haven't put much thought into it because my guess would be as an end consumer they wouldn't see a difference.

> using Maps in scopes instead of objects and some other niche tweaks.

Same question, what's the motivation here? A little faster? I don't see any reason not to use Maps

**Comment by Lutymane** [comment]
You can see all the changes here: https://github.com/Lutymane/glsl-parser/commits/modern-package%2Bmaps

ES modules provide native named exports to use in modern ES projects, which didn't work properly for me when it was CommonJS, building it as CommonJS also adds more bloat, with ES the tree shaking is effective.

Maps are faster and they provide native, convenient and fast iteration with `for-of` loop.

**Pull request merged**
