### PR TITLE
Cleanup comment removal + documentation + release

### PR DESCRIPTION
**Pull request by AndrewRayCode**
Spelling, comments I don't care about anymore, forgot to add error.d.ts apparently, it was getting published, but not in source control!

### CODE REVIEW

**Comment by davepagurek** [comment]
Sounds good, I can also understand the behaviour being potentially confusing, so following Babel's lead makes sense. let me know what you find!

**Comment by AndrewRayCode** [comment]
It looks like babel does continue to visit the nodes you replace. Here's an example replacing a function call - and it has infinite recursion because it looks like it keeps visitng the replaced node https://codesandbox.io/p/sandbox/ast-forked-r9fpyx?file=%2Fsrc%2Findex.js%3A25%2C33 (warning this codesandbox triggers a maximum call stack)

I think there's another parity change to make for babel, which is the replacer node itself should also get visited, not just its children

**Comment by davepagurek** [comment]
Ahh ok right, want me to make a PR adjusting my changes from earlier to just traverse the replaced node directly if it exists?

**Comment by AndrewRayCode** [comment]
@davepagurek if you are up for it that would be great! I was going to look at it this weekend, if you get to it before then that would be awesome. I'll merge rest of the clean-up changes in this PR. 

I think there should be a test for the visit behavior explicitly. LIke, in the test, visiting an identifier, replacing it, and in the test verify the replaced node was also visited and that the original node was not visited.

**Pull request merged**
